import Head from "next/head";
import React from "react";

export function Layout({ children, title = "NextJS project" }) {
  return (
    <React.Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen">
        {/* <Header /> */}
        <div className="flex-1">{children}</div>
        {/* <Footer/> */}
      </main>
    </React.Fragment>
  );
}
